name: 'Protoconf Insert Action'
author: 'Protoconf'
description: 'Insert latest protoconf changes to store'
inputs:
  store_type:
    description: 'etcd/consul/zookeeper'
    required: true
    default: ''
  store_address:
    description: 'Address of the kv store'
    required: true
    default: ''
  prefix:
    description: 'Where should the change be stored'
    required: true
    default: ''
  delete:
    description: 'Delete files from store'
    required: false
    default: false
  changes_only:
    description: 'Whether to insert all keys or only keys which had changes'
    required: false
    default: true
  bulk_size:
    description: 'The bulk size to pass for xargs'
    required: false
    default: 50
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    STORE_ADDRESS: ${{ inputs.store_address }}
    BEFORE_COMMIT: ${{ github.event.before }}
    AFTER_COMMIT: ${{ github.event.after }}
  args:
    - ${{ inputs.store_type }}
    - ${{ inputs.prefix }}
    - ${{ inputs.delete }}
    - ${{ inputs.changes_only }}
    - ${{ inputs.bulk_size }}
branding:
  icon: 'box'
  color: 'green'
